### ISSUE TITLE
Need to use remote.require

### ISSUE THREAD

**Issue by 1j01** [mixmaxhq/electron-spell-check-provider#1]
The documentation should be updated.
https://github.com/mixmaxhq/electron-editor-context-menu/issues/1

**Comment by 1j01** [comment]
I'd also suggest revising the installation section so people don't get `A dynamic link library (DLL) initialization routine failed` before looking back at the README. Something like:

## Installation
First, install the module:
```
npm install electron-spell-check-provider --save
```
Then, since this uses a native module, you need to [rebuild after installing](https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md#the-easy-way).

**Comment by wearhere** [comment]
The installation section here does say that :) https://github.com/mixmaxhq/electron-spell-check-provider#installation

**Comment by wearhere** [comment]
This module does not need `remote.require` since it is not a main process module, unlike `electron-editor-context-menu` which uses `menu`. I just checked and we're just using `require` in our app. Are you getting an error when just using `require`?

**Comment by 1j01** [comment]
@wearhere I know, I reworded it so people like me won't ignore the important bit. 

*Note*: basically nobody reads notes and basically no one is going to know to do the rebuild step.

And yes, that is the module I'm refering to. From this repo's readme: 
```js
var buildEditorContextMenu = require('electron-editor-context-menu');
```

**Comment by wearhere** [comment]
I just noticed that you had been referring to `require('electron-editor-context-menu')`  and not `require('electron-spell-check-provider')` @1j01, my bad!

I respectfully decline to move the installation instructions up. I think it scans much better as is, and most people likely to overlook the installation instructions immediately following the one-liner would also skip _over_ the installation instructions to get to that one-liner. (Plus, without reading the installation and usage sections, how do you even know how to import `SpellCheckProvider`? That's not guaranteed to be the single import of the module.)

Thanks for the report!

**Comment by 1j01** [comment]
Okay, but why is a mandatory installation step a "note"? We could at least replace "don't forget to" with "you need to", because virtually no-one is going to "remember" to do this because it will be the first time they've ever used a native module, let alone one in electron.

**Comment by wearhere** [comment]
The reason to say "note" is to italicize it to draw people's attention to it.

I have tweaked the language following that, please let me know if you find it satisfactory.

**Comment by 1j01** [comment]
Yeah, that's much better. :+1:
