### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by PaulKeefe** [mixmaxhq/electron-spell-check-provider#10]
I get this error in the chrome console:
Uncaught Error: Module version mismatch. Expected 50, got 48.

It happens on this line:
var SpellCheckProvider = require('electron-spell-check-provider');

This seems to be a mismatch with electron 1.4.3 according to this discussion: [https://github.com/electron/electron/issues/5851](https://github.com/electron/electron/issues/5851)

Is this due to the build using electron version 1.2.x?

Is there a way to update it to use the version below?
Electron version: 1.4.0
NODE_MODULE_VERSION: 50
V8 version: 5.3

**Comment by PaulKeefe** [comment]
This issue is actually in the underlying SpellChecker module.

**Comment by wearhere** [comment]
Hi @PaulKeefe, I think that this might actually be because this module (a native module) has not been rebuilt to match the version of Electron you're using. I was getting this error using Electron 1.4.3, electron-spell-check-provider 1.1.0, and electron-rebuild 1.2.1 and then this fixed it for me:

```js
var exec = require('child_process').exec;
var electronRebuild = require('electron-rebuild');
var path = require('path');

var ELECTRON_VERSION = '1.4.3';

var appDir = /* directory of your package.json */;

exec("npm install && npm prune", {cwd: appDir}, function(err, res) {
  electronRebuild.installNodeHeaders(ELECTRON_VERSION)
    .then(() => electronRebuild.rebuildNativeModules(ELECTRON_VERSION, path.join(appDir, 'node_modules')));
});
```

(The above is extracted from a larger build process so might not quite work as written but the gist is hopefully clear.)

**Comment by PaulKeefe** [comment]
Thanks @wearhere I'll give it a try.

**Comment by PaulKeefe** [comment]
That was it. Thanks @wearhere!

**Comment by wearhere** [comment]
Great to hear @PaulKeefe !

**Comment by PaulKeefe** [comment]
@wearhere I now get this: SpellCheckProvider is not a constructor

Do you think this is something wrong in the build process as well?

**Comment by PaulKeefe** [comment]
Oops, I had to change the way I loaded like a module from this:
const {SpellCheckProvider} = require('electron-spell-check-provider');

to this:
var SpellCheckProvider = require('electron-spell-check-provider'); 

Working great now! Thanks @wearhere for the code help.
