### ISSUE TITLE
Please release v1.1.0 to npm

### ISSUE THREAD

**Issue by jhuckaby** [mixmaxhq/electron-spell-check-provider#13]
electron-spell-check-provider v1.1.0 was tagged back on August 24, 2016, but npm still only has v1.0.0.  So if you install from npm, you don't get `add()` for add to dictionary.

Is there any way you can type "npm publish" on your v1.1.0 repo?

Thanks!

**Comment by philfreo** [comment]
@wearhere Can you do this?

**Comment by wearhere** [comment]
Published! Sorry about the delay folks.

**Comment by jhuckaby** [comment]
Thank you!  Much appreciated.
