### ISSUE TITLE
Add method for adding words to dictionary

### ISSUE THREAD

**Issue by skewart** [mixmaxhq/electron-spell-check-provider#5]
Would you guys be open to adding functionality for adding a word to the dictionary?  I'm imagining something that is just a wrapper around node-spellchecker's `add` method.   I'm happy to submit a PR with the change.

**Comment by wearhere** [comment]
Sure thanks @skewart! Further comments on the PR.

**Comment by wearhere** [comment]
Fixed by #6 if I'm not mistaken
